*
PROCEDURE Var_1200w
 PUBLIC viTe, ciTe, xiTe, viT1, xiT1, ciTx, vlIn, vpAg, vsW0, vsW1, vsW2,  ;
        vsW3, vsW9
 PUBLIC vsWa, vsWw, csWw, vsWr, viOm, viMm, vuCo, vcO0, vcO1, vfI2, vcO2,  ;
        vcO3, vcL0
 PUBLIC vcL1, vcL2, vcL3, vcL4, vcL5, vcL6, vcL7, vtM1, vtM2, vtM3, vtM4,  ;
        icLn, ucLn
 PUBLIC icL1, ucL1, vfIl, ifIl, ufIl, ffIl, cfIl, xfIl, vfFs, ifFs, ufFs,  ;
        ffFs, cfFs
 PUBLIC vfFr, ifFr, ufFr, ffFr, cfFr, vfFt, ifFt, ufFt, ffFt, cfFt, vfFu,  ;
        ifFu, ufFu
 PUBLIC ffFu, cfFu, vfFv, ifFv, ufFv, ffFv, cfFv, vfFw, ifFw, ufFw, ffFw,  ;
        cfFw, vfFx
 PUBLIC ifFx, ufFx, ffFx, cfFx, vfB1, vfB2, vfB3, vfB4, vfB5, vfB6, vfB7,  ;
        vfB8, vfB9
 PUBLIC vcB1, vcB2, vcB3, vcB4, vcB5, vcB6, vcB7, vcB8, vcB9, vuLt, vtDo,  ;
        itDo, utDo
 PUBLIC xtDo, vtD1, ctD1, vsEr, isEr, usEr, xsEr, vsE1, vdOc, idOc, udOc,  ;
        xdOc, vdO1
 PUBLIC cdO1, vdIa, idIa, udIa, cdIa, xdIa, vmEs, imEs, umEs, xmEs, vaNo,  ;
        iaNo, uaNo
 PUBLIC xaNo, vnOm, inOm, unOm, xnOm, cnOm, vtB1, vtB2, vtB3, vtB4, vtB5,  ;
        vtB6, vpOp
 PUBLIC vrEc, irEc, urEc, frEc, crEc, vrCc, irCc, urCc, frCc, crCc, vfEm,  ;
        vtCa, vtC1
 PUBLIC vtC2, vtC3, vtC4, vfPa, vnFp, vtFp, vdI1, vvEn, vnVe, vcOm, vtIt,  ;
        xtIt, ctIt
 PUBLIC vnTt, vcLi, xcLi, vrUc, crUc, vdNi, cdNi, vtEl, vtCl, vnTi, vdTc,  ;
        vdMc, vdCl
 PUBLIC vcRe, vmDd, vmD1, xmD1, vmD2, xmD2, vmD3, xmD3, vlIs, ulIs, ulI2,  ;
        ulI3, vsUc
 PUBLIC vnSu, vdIr, cdIr, vdIs, cdIs, vdEp, cdEp, vlUg, vlUd, vlUp, vmOn,  ;
        vsIg, vpIg
 PUBLIC vcM1, vcM2, vpGd, vdCt, xdCt, vsWg, veSt, vpIe, xpIe, vvAl, tvAl,  ;
        tvL1, tvL2
 PUBLIC vnEt, tnEt, tiGv, vtOt, ttOt, vpRe, cpRe, xpRe, vpRo, cpRo, xpRo,  ;
        vpR1, cpR1
 PUBLIC xpR1, vlAr, vlA1, vlA2, vlA3, vlA4, vlA5, vlA6, vlA7, vlA8, vlA9,  ;
        xlAr, xlA1
 PUBLIC xlA2, xlA3, xlA4, xlA5, xlA6, xlA7, xlA8, xlA9, clAr, clA1, clA2,  ;
        clA3, clA4
 PUBLIC clA5, clA6, clA7, clA8, clA9, ilAr, ilA1, zlA1, ilA2, zlA2, ilA3,  ;
        ilA4, ilA5
 PUBLIC ilA6, ilA7, ilA8, ilA9, nlAr, nlA1, nlA2, nlA3, nlA4, nlA5, nlA6,  ;
        nlA7, nlA8
 PUBLIC nlA9, vaNc, vaN1, zaN1, vaN2, zaN2, vaN3, vaN4, vaN5, vaN6, vaN7,  ;
        vaN8, vaN9
 PUBLIC xaNc, xaN1, xaN2, xaN3, xaN4, xaN5, xaN6, xaN7, xaN8, xaN9, caNc,  ;
        caN1, caN2
 PUBLIC caN3, caN4, caN5, caN6, caN7, caN8, caN9, iaNc, iaN1, iaN2, iaN3,  ;
        iaN4, iaN5
 PUBLIC iaN6, iaN7, iaN8, iaN9, naNc, naN1, naN2, naN3, naN4, naN5, naN6,  ;
        naN7, naN8
 PUBLIC naN9, vaLt, vaL1, vaL2, vaL3, vaL4, vaL5, vaL6, vaL7, vaL8, vaL9,  ;
        xaLt, xaL1
 PUBLIC xaL2, xaL3, xaL4, xaL5, xaL6, xaL7, xaL8, xaL9, caLt, caL1, caL2,  ;
        caL3, caL4
 PUBLIC caL5, caL6, caL7, caL8, caL9, iaLt, iaL1, iaL2, iaL3, iaL4, iaL5,  ;
        iaL6, iaL7
 PUBLIC iaL8, iaL9, naLt, naL1, naL2, naL3, naL4, naL5, naL6, naL7, naL8,  ;
        naL9, vcOd
 PUBLIC ccOd, xcOd, ccO1, vcDg, icDg, ucDg, ccDg, vdEs, xdEs, zdEs, vdCr,  ;
        cdCr, xdCr
 PUBLIC vdCc, idCc, udCc, cdCc, vcUv, ccUv, xcUv, vnUv, cnUv, xnUv, znUv,  ;
        vcUc, xcUc
 PUBLIC vnUc, xnUc, vmEd, xmEd, vcAn, ccAn, xcAn, vsOl, xsOl, vuSd, xuSd,  ;
        vpDc, xpDc
 PUBLIC vrEf, xrEf, veSp, xeSp, vtO1, xtO1, vtO2, xtO2, vpEs, xpEs, vtIp,  ;
        xtIp, vtPo
 PUBLIC itPo, utPo, xtPo, ctPo, vnTp, inTp, unTp, cnTp, vlEt, vsTo, vcSt,  ;
        vsRr, vfOt
 PUBLIC cfOt, cfT1, vmV1, vmV2, voPc, vuN1, vuN2, vmLa, cmLa, vmAn, cmAn,  ;
        vp11, cp11
 PUBLIC vp12, vp21, cp21, vp22, vcTd, vtPi, vfOr, cfOr, vdSp, cdSp, vdSt,  ;
        vtTt, ctTt
 PUBLIC vnEm, vtI1, vtI2, vtI3, vtI4, voP1, ioP1, uoP1, coP1, vdC1, idC1,  ;
        udC1, cdC1
 PUBLIC tdC1, voP2, ioP2, uoP2, coP2, vdC2, idC2, udC2, cdC2, tdC2, voP3,  ;
        ioP3, uoP3
 PUBLIC coP3, vdC3, idC3, udC3, cdC3, tdC3, voP4, ioP4, uoP4, coP4, vdC4,  ;
        idC4, udC4
 PUBLIC cdC4, voP5, ioP5, uoP5, coP5, vdC5, idC5, udC5, cdC5, voP6, ioP6,  ;
        uoP6, coP6
 PUBLIC vdC6, idC6, udC6, cdC6, voP7, ioP7, uoP7, coP7, vdC7, idC7, udC7,  ;
        cdC7, vnUm
 PUBLIC vnU1, vnU2, csR1, cnDo, cfEm, cpRv, vfRa, veNt, vsWx, voPp, vbOr,  ;
        tpSo, vcA1
 PUBLIC vcA2, vcA3, vcA4, vmM1, vmM2, vmM3, vmM4, vcX1, vcX2, vcX3, vcX4,  ;
        vcY1, vcY2
 PUBLIC vcY3, vcY4, vpOr, vgRa, vcMm, vcMp, vpEr, xpEr, vpPe, viPe, tpEr,  ;
        tnPe, vdTr
 PUBLIC xdTr, vnPe, vtDd, vdPp, xdPp, tdPp, vcOn, vtDi, vlEc, vnTe
 PUBLIC vpAn_11, vpAn_12, vpAn_let, vpAn_le1, vpAn_le2, vpAn_le3, vpAn_le4
 PUBLIC vpAn_le5
 Define Popup vPOP Margin Relative Color Scheme 6 Font "&mLetRom",14 Style "NQ"
 DEFINE BAR 1 OF vpOp PROMPT "1"
 STORE SPACE(01) TO vdPp, tdPp
 STORE SPACE(02) TO vtDd
 DO CASE
      CASE mlSt=2
           DEFINE BAR 2 OF vpOp PROMPT "2"
      CASE mlSt=3
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
      CASE mlSt=4
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
      CASE mlSt=5
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
      CASE mlSt=6
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
           DEFINE BAR 6 OF vpOp PROMPT "6"
      CASE mlSt=7
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
           DEFINE BAR 6 OF vpOp PROMPT "6"
      CASE mlSt=8
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
           DEFINE BAR 6 OF vpOp PROMPT "6"
           DEFINE BAR 7 OF vpOp PROMPT "7"
           DEFINE BAR 8 OF vpOp PROMPT "8"
      CASE mlSt=9
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
           DEFINE BAR 6 OF vpOp PROMPT "6"
           DEFINE BAR 7 OF vpOp PROMPT "7"
           DEFINE BAR 8 OF vpOp PROMPT "8"
           DEFINE BAR 9 OF vpOp PROMPT "9"
      CASE mlSt=10
           DEFINE BAR 2 OF vpOp PROMPT "2"
           DEFINE BAR 3 OF vpOp PROMPT "3"
           DEFINE BAR 4 OF vpOp PROMPT "4"
           DEFINE BAR 5 OF vpOp PROMPT "5"
           DEFINE BAR 6 OF vpOp PROMPT "6"
           DEFINE BAR 7 OF vpOp PROMPT "7"
           DEFINE BAR 8 OF vpOp PROMPT "8"
           DEFINE BAR 9 OF vpOp PROMPT "9"
           DEFINE BAR 10 OF vpOp PROMPT "10"
 ENDCASE
 ON SELECTION POPUP vpOp DO OP1_1200W WITH POPUP() IN PVI1200W
 DO liM_1200w IN PVI1200W
 STORE SPACE(07) TO vdOc
ENDPROC
*
PROCEDURE Op1_1200w
 PARAMETER ppOp
 STORE BAR() TO vlIs
 DO coLbln
 @mMF1+1.1,1.9 Say StrTran(Str(vLIS,2,0)," ","0") Font "&mLetRom",12 Style "BQ" Size 1,2.3
 DEACTIVATE POPUP vpOp
ENDPROC
*
PROCEDURE Lim_1200w
 STORE "PE" TO vtDo
 STORE "6" TO vtDi
 STORE 01 TO irEc, vrEc, viOm, viMm, viTe, vsW0, vsW3, vsW9, vsWa, vsWg, ulIs
 STORE 00 TO frEc, urEc, crEc, cfIl, viT1, vcOm, vdTc, vdMc, vdCl, vpGd,  ;
       vtOt, vcAn
 STORE 00 TO tvAl, tpEr, vnSu, vmDd, tnPe, vnPe, ulI2, ulI3, vcA1, vcA2,  ;
       vcA3, vcA4
 STORE 02 TO vcRe, vpEr, vdTr
 STORE 99 TO mkEy
 STORE 88 TO mpAg
 STORE mlIs TO vlIs
 STORE miGv TO vpIg
 STORE mmOn TO vmOn
 STORE mpPe TO vpPe
 STORE DATE() TO vfEm
 STORE SPACE(01) TO vdPp
 STORE SPACE(03) TO vcMm
 STORE SPACE(06) TO vcOd
 STORE SPACE(07) TO vtEl
 STORE SPACE(11) TO vrUc
 STORE SPACE(20) TO vcMp
 STORE SPACE(90) TO vcM2
 STORE SPACE(15) TO vdNi, cdNi
 STORE SPACE(50) TO vnTi, vnVe
 STORE SPACE(02) TO vsUc, vtCl, vvEn
 STORE SPACE(04) TO vcLi, xcLi, vtIt
 STORE SPACE(25) TO vdIs, vdEp, vlUd, vlUp, vcOn
 STORE SPACE(70) TO vnOm, vdIr, vcM1, vlUg, vnTt, vdEs, vnTe
 DO CASE
      CASE vmOn=1
           STORE msIg TO vsIg
      CASE vmOn=2
           STORE "US$" TO vsIg
 ENDCASE
 SELECT caMbio
 SEEK vfEm
 IF EOF()
      GOTO BOTTOM
      IF EOF()
           STORE 1 TO vtCa
      ELSE
           STORE f9111tc1 TO vtC1
           STORE f9111tc2 TO vtC2
           STORE f9111tc3 TO vtC3, vtCa
           STORE f9111tc4 TO vtC4
           DO nuEvo_rg
           REPLACE f9111fem WITH vfEm
           REPLACE f9111tc1 WITH vtC1
           REPLACE f9111tc2 WITH vtC2
           REPLACE f9111tc3 WITH vtC3
           REPLACE f9111tc4 WITH vtC4
           UNLOCK
           FLUSH
      ENDIF
 ELSE
      STORE f9111tc3 TO vtCa
 ENDIF
 SELECT paGos
 GOTO TOP
 STORE f9112fpa TO vfPa
 STORE f9112nfp TO vnFp
 STORE f9112tip TO vtFp
 STORE f9112dia TO vdI1
 IF LEN(ALLTRIM(mvEn))<>0
      STORE mvEn TO vvEn
      SELECT veNdedor
      SEEK vvEn
      IF EOF()
           STORE SPACE(50) TO vnVe
           STORE 0 TO vcOm
      ELSE
           STORE f9113nom TO vnVe
           STORE f9113com TO vcOm
      ENDIF
 ENDIF
ENDPROC
*
PROCEDURE Bot_1200w
 PARAMETER ptPo
 DO CASE
      CASE ptPo="3"
           DO prEsiona WITH "3", "VARIOS", vfB1, vcB1
      CASE vsW0=1
           DO prEsiona WITH "1", "VARIOS", vfB1, vcB1
      CASE vsW0=2
           DO prEsiona WITH "2", "VARIOS", vfB1, vcB1
 ENDCASE
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO CASE
      CASE ptPo="3" .OR. vsW0=2
           DO prEsiona WITH "3", "CONSUL", vfB2, vcB2
           DO prEsiona WITH "3", "BUSCAR", vfB3, vcB3
      CASE vsW0=1
           DO prEsiona WITH "1", "CONSUL", vfB2, vcB2
           DO prEsiona WITH "1", "BUSCAR", vfB3, vcB3
 ENDCASE
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO CASE
      CASE ptPo="3" .OR. LEN(ALLTRIM(vcLi))=0 .OR. vnSu<=1
           DO prEsiona WITH "3", "CONSUL", vfB5, vcB5
      OTHERWISE
           DO prEsiona WITH "1", "CONSUL", vfB5, vcB5
 ENDCASE
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO prEsiona WITH ptPo, "DESCAR", vfB4, vcB4
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO prEsiona WITH ptPo, "CONSUL", vfB6, vcB6
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO prEsiona WITH ptPo, "CONSUL", vfB7, vcB7
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO CASE
      CASE ptPo="3" .OR. vsW0=1
           DO prEsiona WITH "3", "CONSUL", vfB8, vcB8
      OTHERWISE
           DO prEsiona WITH "1", "CONSUL", vfB8, vcB8
 ENDCASE
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO CASE
      CASE ptPo="3" .OR. LEN(ALLTRIM(vtIt))=0 .OR. vsW0=1
           DO prEsiona WITH "3", "DESCAR", vfB9, vcB9
      OTHERWISE
           DO prEsiona WITH "1", "DESCAR", vfB9, vcB9
 ENDCASE
 IF mkEy=k_Esc
      RETURN
 ENDIF
ENDPROC
*
PROCEDURE Per_1200w
 IF vlEc=2
      RETURN
 ENDIF
 DO coLbln
 @ ffIl+1.1, mcO0+muCo-22.6 TO ffIl+3.6, mcO0+muCo-0.1 PATTERN 1
 @fFIL+1.2,mCO0+mUCO-21.6 Say "PERC:"   Font "&mLetAri",9 Style "BQ"
 @fFIL+1.2,mCO0+mUCO-14.6 Say tPER      Font "&mLetAri",9 Style "BQ" Pict "999,999.99" Size 1,11.6
 @fFIL+2.4,mCO0+mUCO-21.6 Say "T+PE:"   Font "&mLetAri",9 Style "BQ"
 IF tpEr+ttOt>999999
      @fFIL+2.4,mCO0+mUCO-14.6 Say tPER+tTOT Font "&mLetAri",9 Style "BQ" Pict "9,999,999"  Size 1,11.6
 ELSE
      @fFIL+2.4,mCO0+mUCO-14.6 Say tPER+tTOT Font "&mLetAri",9 Style "BQ" Pict "999,999.99" Size 1,11.6
 ENDIF
ENDPROC
*
PROCEDURE Acc_1200w
 PARAMETER ptPo
 IF msUn=" " .OR. mfDe<>CTOD(" ") .OR. DATE()>mfHa
      RETURN
 ENDIF
 IF msUn$"AB" .AND. (mfDe=CTOD(" ") .OR. DATE()>mfHa)
      DO prEsiona WITH "1", "BLANNO", mmF1+0.3, 10
 ELSE
      DO prEsiona WITH "1", "BLANCO", mmF1+0.3, 10
 ENDIF
 IF mkEy=k_Esc
      RETURN
 ENDIF
 DO coLbln
 DO CASE
      CASE msUn=" "
           @mMF1+0.4,10.9 Say "Sin acceso" Font "&mLetRom",12 Style "BT"
           @mMF1+1.4,10.9 Say "a SUNAT"    Font "&mLetRom",12 Style "BT"
      CASE msUn="A"
           @mMF1+0.4,12.3 Say "SUNAT"      Font "&mLetRom",12 Style "BT"
           @mMF1+1.4,11.3 Say "Avanzado"   Font "&mLetRom",12 Style "BT"
      CASE msUn="B"
           @mMF1+0.4,12.3 Say "SUNAT"      Font "&mLetRom",12 Style "BT"
           @mMF1+1.4,12.9 Say "Basico"     Font "&mLetRom",12 Style "BT"
 ENDCASE
 IF msUn$"AB" .AND. DATE()+7>mfHa .AND. DATE()<=mfHa .AND. ptPo="1"
      STORE CHR(13)+"ACCESO A LA SUNAT VENCE EL "+DTOC(mfHa)+"..."+ ;
            CHR(13) TO mmSj
      DO poNmsj
 ENDIF
ENDPROC
*
PROCEDURE Lin_1200w
 PARAMETER piNi, pfIn
 DO coLsc3
 DO CASE
      CASE mrEs="3"
           @ piNi, vcO1+003.2 TO pfIn, vcO1+003.2
           @ piNi, vcO1+064.8 TO pfIn, vcO1+064.8
           @ piNi, vcO1+078.0 TO pfIn, vcO1+078.0
           @ piNi, vcO1+095.1 TO pfIn, vcO1+095.1
           @ piNi, vcO1+112.3 TO pfIn, vcO1+112.3
           @ piNi, vcO1+121.0 TO pfIn, vcO1+121.0
           @ piNi, vcO1+137.6 TO pfIn, vcO1+137.6
           @ piNi, vcO1+180.9 TO pfIn, vcO1+180.9
      OTHERWISE
           @ piNi, vcO1+003.2 TO pfIn, vcO1+003.2
           @ piNi, vcO1+064.8 TO pfIn, vcO1+064.8
           @ piNi, vcO1+078.0 TO pfIn, vcO1+078.0
           @ piNi, vcO1+095.1 TO pfIn, vcO1+095.1
           @ piNi, vcO1+112.3 TO pfIn, vcO1+112.3
           @ piNi, vcO1+121.0 TO pfIn, vcO1+121.0
           @ piNi, vcO1+137.6 TO pfIn, vcO1+137.6
           @ piNi, vcO1+180.9 TO pfIn, vcO1+180.9
 ENDCASE
ENDPROC
*
PROCEDURE Pig_1200w
 DO CASE
      CASE mpIg=2
           DO coLsc6
      OTHERWISE
           DO coLbln
 ENDCASE
 @mFI0+4.2,vCL5-0.2 Say "  " Font "&mLetAri",9 Style "NQ" Size 1,0.2
 @mFI0+4.2,vCL5     Say vPIG Font "&mLetAri",9 Style "NQ" Size 1,7.3 Pict "99.99"
 @mFI0+4.2,vCL5+7.4 Say "  " Font "&mLetAri",9 Style "NQ" Size 1,0.4
ENDPROC
*
PROCEDURE Nom_1200w
 DO CASE
      CASE vsW0=1
           DO coL_beige
      CASE vsW0=3
           DO coL_fondo
      OTHERWISE
           DO coLbln
 ENDCASE
 @mFI0+1,mCO0+13.5 Say Substr(vNOM,1,vTM1+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM1
ENDPROC
*
PROCEDURE Drc_1200w
 DO CASE
      CASE vsW0=1
           DO coL_beige
      OTHERWISE
           DO coLbln
 ENDCASE
 @mFI0+2.5,mCO0+13.5 Say Substr(vDIR,1,vTM1+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM1
 @mFI0+4.0,mCO0+13.5 Say Substr(vDIS,1,vTM2+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM2
 @mFI0+4.0,vCL1      Say Substr(vDEP,1,vTM2+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM2
ENDPROC
*
PROCEDURE Ruc_1200w
 DO CASE
      CASE vsW0=1
           DO coL_beige
      OTHERWISE
           DO coLbln
 ENDCASE
 @mFI0+4,vCL2     Say vRUC Font "&mLetAri",9 Style "NQ" Size 1,15.7
 @mFI0+4,vCL3+0.7 Say vDNI Font "&mLetAri",9 Style "NQ" Size 1,11.7 Pict "@S15"
ENDPROC
*
PROCEDURE Lug_1200w
 DO coLbln
 @mFI0+5.5,mCO0+13.5 Say Substr(vLUG,1,vTM3+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM3
 @mFI0+7.0,mCO0+13.5 Say Substr(vLUD,1,vTM2+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM2
 @mFI0+7.0,vCL1      Say Substr(vLUP,1,vTM2+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM2
ENDPROC
*
PROCEDURE Dve_1200w
 DO coLsc6
 @mFI0+6,vCL4 Say Substr(vNVE,1,vTM4+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM4
ENDPROC
*
PROCEDURE Dct_1200w
 PARAMETER ptIp
 DO coL_beige
 IF ptIp=1
      @mFI0+12.5,mCO0+085.5 Say vDTC Font "&mLetAri",9 Style "NQ" Size 1,7.9 Pict "999.99"
      @mFI0+12.5,mCO0+115.5 Say vDCL Font "&mLetAri",9 Style "NQ" Size 1,7.9 Pict "999.99"
 ELSE
      @mFI0+12.5,mCO0+085.5 Say vDTC Font "&mLetAri",9 Style "NQ" Size 1,7.9 Pict "999.99"
      @mFI0+12.5,mCO0+115.5 Say vDCL Font "&mLetAri",9 Style "NQ" Size 1,7.9 Pict "999.99"
 ENDIF
ENDPROC
*
PROCEDURE Dti_1200w
 DO coL_beige
 @mFI0+7,vCL6    Say vTIT Font "&mLetAri",9 Style "NQ" Size 1,5.5 Pict "!!!!"
 DO coL_fondo
 @mFI0+7,vCL6+15 Say vNTT Font "&mLetAri",9 Style "NQ" Size 1,17  Pict "@S20"
ENDPROC
*
PROCEDURE Swg_1200w
 PARAMETER prEa
 @mFI0+12.5,mCO0+13.5 Get vSWG Font "&mLetAri",9 Style "NQ" Default vSWG Size 1,4,.1 Function "*RHT x Porcentaje;x Monto" Color RGB(0,0,0,235,231,222)
 IF prEa="S"
      READ TIMEOUT 0.01
 ENDIF
ENDPROC
*
PROCEDURE Nfp_1200w
 DO coLsc6
 @mFI0+2.5,vCL4 Say Substr(vNFP,1,vTM4+3) Font "&mLetAri",9 Style "NQ" Size 1,vTM4
ENDPROC
*
PROCEDURE Tot_1200w
 PARAMETER prEa
 PRIVATE peSp
 DO CASE
      CASE vlEc=1
           IF vmOn=1
                STORE " " TO peSp
           ELSE
                STORE "" TO peSp
           ENDIF
           DO coLsc3
           @fFIL+2.2,vCO1+134 Say pESP+"Total "+vSIG Font "&mLetAri",9 Style "BQ" Size 1,11
           IF vsW3=1
                @mFI0+4.2,vCL4-9.5 Get vMON Font "&mLetAri",9 Style "NQ" Default vMON Size 1,5,1 Function "*RHT S/;US$" Color RGB(0,0,0,235,231,222)
           ENDIF
           IF prEa="S"
                READ TIMEOUT 0.01
           ENDIF
      CASE vlEc=2
           DO coL_boton
           @fFIL+5.8,vCO1+Int(vUCO/2)+60 Say "Total "+vSIG Font "&mLetRom",15 Style "BQ"
 ENDCASE
 RELEASE peSp
ENDPROC
*
PROCEDURE Tca_1200w
 IF vlEc=2
      RETURN
 ENDIF
 DO coLsc6
 @mFI0+1,vCL7 Say vTCA Font "&mLetAri",9 Style "NQ" Size 1,8.3 Pict "99.999"
ENDPROC
*
PROCEDURE Cal_1200w
 STORE vrEc TO crEc
 STORE vfIl TO cfIl
 STORE 00 TO vtOt, tvAl, tpEr, vsW1
 SELECT teMporal
 GOTO TOP
 IF  .NOT. BOF()
      DO WHILE  .NOT. EOF()
           IF vmOn=1
                REPLACE ftM1pre WITH ftM1sol
           ELSE
                REPLACE ftM1pre WITH ftM1usd
           ENDIF
           DO cl1_1200b IN PVI1200B
           STORE tvAl+vtOt TO tvAl
           STORE tpEr+viPe TO tpEr
           SKIP
      ENDDO
      SELECT teMporal
      IF irEc<=frEc
           GOTO irEc
           DO paN_1200b IN PVI1200B
           IF mkEy=k_Esc
                RETURN
           ENDIF
      ELSE
           DO coL_fondo
           @ vfIl, icLn CLEAR TO ffIl+1.1, ucLn
           DO liN_1200w IN PVI1200W WITH vfIl, ffIl+1.1
      ENDIF
 ENDIF
 STORE 01 TO vsW1
 DO ctO_1200b IN PVI1200B
 STORE crEc TO vrEc
 STORE cfIl TO vfIl
ENDPROC
*
PROCEDURE Cal_1300w
 STORE vrEc TO crEc
 STORE vfIl TO cfIl
 STORE 00 TO vtOt, tvAl, tpEr, vsW1
 SELECT teMporal
 GOTO TOP
 IF  .NOT. BOF()
      GOTO BOTTOM
      STORE RECNO() TO frEc
      GOTO TOP
      DO WHILE  .NOT. EOF()
           IF vmOn=1
                REPLACE ftM1pre WITH ftM1sol
           ELSE
                REPLACE ftM1pre WITH ftM1usd
           ENDIF
           DO cl1_1200b IN PVI1200B
           STORE tvAl+vtOt TO tvAl
           STORE tpEr+viPe TO tpEr
           SKIP
      ENDDO
      SELECT teMporal
      IF irEc<=frEc
           GOTO irEc
           DO paN_1200b IN PVI1200B
           IF mkEy=k_Esc
                RETURN
           ENDIF
      ELSE
           DO coL_fondo
           @ vfIl, icLn CLEAR TO ffIl+1.1, ucLn
           DO liN_1200w IN PVI1200W WITH vfIl, ffIl+1.1
      ENDIF
 ENDIF
 STORE 01 TO vsW1
 DO ctO_1200b IN PVI1200B
 STORE crEc TO vrEc
 STORE cfIl TO vfIl
ENDPROC
*
PROCEDURE Del_1200w
 RELEASE viTe, ciTe, xiTe, viT1, xiT1, ciTx, vlIn, vpAg, vsW0, vsW1, vsW2,  ;
         vsW3, vsW9
 RELEASE vsWa, vsWw, csWw, vsWr, viOm, viMm, vuCo, vcO0, vcO1, vfI2, vcO2,  ;
         vcO3, vcL0
 RELEASE vcL1, vcL2, vcL3, vcL4, vcL5, vcL6, vcL7, vtM1, vtM2, vtM3, vtM4,  ;
         icLn, ucLn
 RELEASE icL1, ucL1, vfIl, ifIl, ufIl, ffIl, cfIl, xfIl, vfFs, ifFs, ufFs,  ;
         ffFs, cfFs
 RELEASE vfFr, ifFr, ufFr, ffFr, cfFr, vfFt, ifFt, ufFt, ffFt, cfFt, vfFu,  ;
         ifFu, ufFu
 RELEASE ffFu, cfFu, vfFv, ifFv, ufFv, ffFv, cfFv, vfFw, ifFw, ufFw, ffFw,  ;
         cfFw, vfFx
 RELEASE ifFx, ufFx, ffFx, cfFx, vfB1, vfB2, vfB3, vfB4, vfB5, vfB6, vfB7,  ;
         vfB8, vfB9
 RELEASE vcB1, vcB2, vcB3, vcB4, vcB5, vcB6, vcB7, vcB8, vcB9, vuLt, vtDo,  ;
         itDo, utDo
 RELEASE xtDo, vtD1, ctD1, vsEr, isEr, usEr, xsEr, vsE1, vdOc, idOc, udOc,  ;
         xdOc, vdO1
 RELEASE cdO1, vdIa, idIa, udIa, cdIa, xdIa, vmEs, imEs, umEs, xmEs, vaNo,  ;
         iaNo, uaNo
 RELEASE xaNo, vnOm, inOm, unOm, xnOm, cnOm, vtB1, vtB2, vtB3, vtB4, vtB5,  ;
         vtB6, vpOp
 RELEASE vrEc, irEc, urEc, frEc, crEc, vrCc, irCc, urCc, frCc, crCc, vfEm,  ;
         vtCa, vtC1
 RELEASE vtC2, vtC3, vtC4, vfPa, vnFp, vtFp, vdI1, vvEn, vnVe, vcOm, vtIt,  ;
         xtIt, ctIt
 RELEASE vnTt, vcLi, xcLi, vrUc, crUc, vdNi, cdNi, vtEl, vtCl, vnTi, vdTc,  ;
         vdMc, vdCl
 RELEASE vcRe, vmDd, vmD1, xmD1, vmD2, xmD2, vmD3, xmD3, vlIs, ulIs, ulI2,  ;
         ulI3, vsUc
 RELEASE vnSu, vdIr, cdIr, vdIs, cdIs, vdEp, cdEp, vlUg, vlUd, vlUp, vmOn,  ;
         vsIg, vpIg
 RELEASE vcM1, vcM2, vpGd, vdCt, xdCt, vsWg, veSt, vpIe, xpIe, vvAl, tvAl,  ;
         tvL1, tvL2
 RELEASE vnEt, tnEt, tiGv, vtOt, ttOt, vpRe, cpRe, xpRe, vpRo, cpRo, xpRo,  ;
         vpR1, cpR1
 RELEASE xpR1, vlAr, vlA1, vlA2, vlA3, vlA4, vlA5, vlA6, vlA7, vlA8, vlA9,  ;
         xlAr, xlA1
 RELEASE xlA2, xlA3, xlA4, xlA5, xlA6, xlA7, xlA8, xlA9, clAr, clA1, clA2,  ;
         clA3, clA4
 RELEASE clA5, clA6, clA7, clA8, clA9, ilAr, ilA1, zlA1, ilA2, zlA2, ilA3,  ;
         ilA4, ilA5
 RELEASE ilA6, ilA7, ilA8, ilA9, nlAr, nlA1, nlA2, nlA3, nlA4, nlA5, nlA6,  ;
         nlA7, nlA8
 RELEASE nlA9, vaNc, vaN1, zaN1, vaN2, zaN2, vaN3, vaN4, vaN5, vaN6, vaN7,  ;
         vaN8, vaN9
 RELEASE xaNc, xaN1, xaN2, xaN3, xaN4, xaN5, xaN6, xaN7, xaN8, xaN9, caNc,  ;
         caN1, caN2
 RELEASE caN3, caN4, caN5, caN6, caN7, caN8, caN9, iaNc, iaN1, iaN2, iaN3,  ;
         iaN4, iaN5
 RELEASE iaN6, iaN7, iaN8, iaN9, naNc, naN1, naN2, naN3, naN4, naN5, naN6,  ;
         naN7, naN8
 RELEASE naN9, vaLt, vaL1, vaL2, vaL3, vaL4, vaL5, vaL6, vaL7, vaL8, vaL9,  ;
         xaLt, xaL1
 RELEASE xaL2, xaL3, xaL4, xaL5, xaL6, xaL7, xaL8, xaL9, caLt, caL1, caL2,  ;
         caL3, caL4
 RELEASE caL5, caL6, caL7, caL8, caL9, iaLt, iaL1, iaL2, iaL3, iaL4, iaL5,  ;
         iaL6, iaL7
 RELEASE iaL8, iaL9, naLt, naL1, naL2, naL3, naL4, naL5, naL6, naL7, naL8,  ;
         naL9, vcOd
 RELEASE ccOd, xcOd, ccO1, vcDg, icDg, ucDg, ccDg, vdEs, xdEs, zdEs, vdCr,  ;
         cdCr, xdCr
 RELEASE vdCc, idCc, udCc, cdCc, vcUv, ccUv, xcUv, vnUv, cnUv, xnUv, znUv,  ;
         vcUc, xcUc
 RELEASE vnUc, xnUc, vmEd, xmEd, vcAn, ccAn, xcAn, vsOl, xsOl, vuSd, xuSd,  ;
         vpDc, xpDc
 RELEASE vrEf, xrEf, veSp, xeSp, vtO1, xtO1, vtO2, xtO2, vpEs, xpEs, vtIp,  ;
         xtIp, vtPo
 RELEASE itPo, utPo, xtPo, ctPo, vnTp, inTp, unTp, cnTp, vlEt, vsTo, vcSt,  ;
         vsRr, vfOt
 RELEASE cfOt, cfT1, vmV1, vmV2, voPc, vuN1, vuN2, vmLa, cmLa, vmAn, cmAn,  ;
         vp11, cp11
 RELEASE vp12, vp21, cp21, vp22, vcTd, vtPi, vfOr, cfOr, vdSp, cdSp, vdSt,  ;
         vtTt, ctTt
 RELEASE vnEm, vtI1, vtI2, vtI3, vtI4, voP1, ioP1, uoP1, coP1, vdC1, idC1,  ;
         udC1, cdC1
 RELEASE tdC1, voP2, ioP2, uoP2, coP2, vdC2, idC2, udC2, cdC2, tdC2, voP3,  ;
         ioP3, uoP3
 RELEASE coP3, vdC3, idC3, udC3, cdC3, tdC3, voP4, ioP4, uoP4, coP4, vdC4,  ;
         idC4, udC4
 RELEASE cdC4, voP5, ioP5, uoP5, coP5, vdC5, idC5, udC5, cdC5, voP6, ioP6,  ;
         uoP6, coP6
 RELEASE vdC6, idC6, udC6, cdC6, voP7, ioP7, uoP7, coP7, vdC7, idC7, udC7,  ;
         cdC7, vnUm
 RELEASE vnU1, vnU2, csR1, cnDo, cfEm, cpRv, vfRa, veNt, vsWx, voPp, vbOr,  ;
         tpSo, vcA1
 RELEASE vcA2, vcA3, vcA4, vmM1, vmM2, vmM3, vmM4, vcX1, vcX2, vcX3, vcX4,  ;
         vcY1, vcY2
 RELEASE vcY3, vcY4, vpOr, vgRa, vcMm, vcMp, vpEr, xpEr, vpPe, viPe, tpEr,  ;
         tnPe, vdTr
 RELEASE xdTr, vnPe, vtDd, vdPp, xdPp, tdPp, vcOn, vtDi, vlEc, vnTe
 RELEASE vpAn_11, vpAn_12, vpAn_let, vpAn_le1, vpAn_le2, vpAn_le3, vpAn_le4
 RELEASE vpAn_le5
ENDPROC
*
